### ISSUE TITLE
The CMD application is failing

### ISSUE THREAD

**Issue by sauravsomxz** [amannirala13/Youtube-Downloader---ytd#1]
After giving the link, it is showing, "Loading Video" then an unhandled exception. 
PFA - SS for ref.

![image](https://user-images.githubusercontent.com/38918625/120588399-bd783200-c454-11eb-94fd-e47cf418b132.png)

**Comment by amannirala13** [comment]
> 
> 
> After giving the link, it is showing, "Loading Video" then an unhandled exception.
> PFA - SS for ref.
> 
> ![image](https://user-images.githubusercontent.com/38918625/120588399-bd783200-c454-11eb-94fd-e47cf418b132.png)

Thanks for reporting. I was able to reproduce the error and looking into it.

**Comment by amannirala13** [comment]
Issue #1 has been fixed in the f04d2b53a7043feed8baf5118fc77f3e8408c9e8 and a new release has been published. Download [0.1.3](https://github.com/amannirala13/Youtube-Downloader---ytd/releases/tag/0.1.3)
